name: typed_json_getters
description: A Dart library providing type-safe getters for JSON maps with robust error handling.
version: 0.0.2
repository: https://github.com/FrenkyDema/typed_json_getters

environment:
  sdk: ^3.5.2


dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
