contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/ristocloud-group/app-lib-typed-json-getters/discussions/categories/q-a
    about: Open a new question in the discussion section.
